pipeline {
    agent any
    environment{
        My_Project= "Jenkins"
        appVersion = ""
    }
    options {
        timeout(time: 10, unit: 'MINUTES')
        disableConcurrentBuilds()
    }
    stages {
        stage('Read Version') {
            steps {
                script {
                    def packageJSON = readJSON file: 'package.json'
                    appVersion = packageJSON.Version
                    echo "app version : ${appVersion}"

                }
            }
        }

        stage('Test') {
            steps {
                script {
                    sh"""
                       echo 'Testing application...'
                    """
                }
            }
        }

        stage('Deploy') {
            steps {
                script {
                    sh"""
                       echo 'deploying application...'
                    """
                }
            }
        }
    }
    
    post {
        always {
            echo 'Pipeline finished.'
            cleanWs() 
        }
        success {
            echo 'Success! Sending notification...'
        }
        failure {
            echo 'Failed. Check the logs.'
        }
    }
}
